#LOADING THE DATASETS

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [46]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

In [100]:
df1 = pd.read_excel(r"C:\Users\Ozoha\Documents\.ipynb_checkpoints\credit-risk-ews\data\raw\Raw 1.xlsx", sheet_name = "Sheet1")
df2 = pd.read_excel(r"C:\Users\Ozoha\Documents\.ipynb_checkpoints\credit-risk-ews\data\raw\Raw 3.xlsx", sheet_name = "Sheet2")

In [101]:
df1.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP_ENTITY_NAME,SP_ENTITY_ID,SP_COMPANY_NAME,SP_ENTITY_ID,SP_TICKER,IQ_TOTAL_ASSETS,IQ_TOTAL_ASSETS,IQ_TOTAL_ASSETS,IQ_TOTAL_ASSETS,IQ_TOTAL_ASSETS,IQ_TOTAL_ASSETS,IQ_TOTAL_REV,IQ_TOTAL_REV,IQ_TOTAL_REV,IQ_TOTAL_REV,IQ_TOTAL_REV,IQ_TOTAL_REV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_LT_DEBT,IQ_LT_DEBT,IQ_LT_DEBT,IQ_LT_DEBT,IQ_LT_DEBT,IQ_LT_DEBT,IQ_CASH_OPER,IQ_CASH_OPER,IQ_CASH_OPER,IQ_CASH_OPER,IQ_CASH_OPER,IQ_CASH_OPER
4,NaN,NaN,NaN,NaN,NaN,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,@Plan.Inc (NASDAQGM:APLN),4996297,@Plan.Inc,4996297,APLN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1606 Corp. (OTCPK:CBDW),29580758,1606 Corp.,29580758,CBDW,NaN,10.14,148.338,231.816,40.992,50.347,NaN,7.195,1.603,13.944,34.069,67.907,NaN,2.078,48.941,105.065,9.543,NaN,NaN,1553.856,1001.636,NaN,195.05,NaN,NaN,NaN,NaN,735.05,36.422,NaN,NaN,-890.986,-747.104,-610.151,-260.507,-95.289
8,1-800 AutoTow Inc. (OTCPK:AUTW),4984380,1-800 AutoTow Inc.,4984380,AUTW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,"1-800-FLOWERS.COM, Inc.",4122591,FLWS,772617,1032648,1051430,1094891,1076679,774435,1685658,1831421,2017853,2207885,2122245,1489637,46502,159437,126807,31465,173573,240506,NaN,NaN,NaN,NaN,NaN,NaN,134764,177113,186391,142497,161512,87559,-26363,94999,115351,5189,173290,139417

In [102]:
df2.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP_ENTITY_NAME,SP_ENTITY_ID,IQ_EBIT,IQ_EBIT,IQ_EBIT,IQ_EBIT,IQ_EBIT,IQ_EBIT,IQ_EBITDA,IQ_EBITDA,IQ_EBITDA,IQ_EBITDA,IQ_EBITDA,IQ_EBITDA,IQ_INTEREST_EXP,IQ_INTEREST_EXP,IQ_INTEREST_EXP,IQ_INTEREST_EXP,IQ_INTEREST_EXP,IQ_INTEREST_EXP,PCD_TOTAL_LIAB,PCD_TOTAL_LIAB,PCD_TOTAL_LIAB,PCD_TOTAL_LIAB,PCD_TOTAL_LIAB,PCD_TOTAL_LIAB,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_ST_DEBT,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV,IQ_CASH_EQUIV
4,NaN,NaN,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2024,FY2023,FY2025,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020,FY2025,FY2024,FY2023,FY2022,FY2021,FY2020
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,@Plan.Inc (NASDAQGM:APLN),4996297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1606 Corp. (OTCPK:CBDW),29580758,NaN,-4116.775,-1554.972,-540.037,-301.261,-227.742,NaN,NaN,NaN,NaN,NaN,NaN,-491.385,-153.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1553.856,1001.636,NaN,195.05,NaN,NaN,2.078,48.941,105.065,9.543,NaN
8,1-800 AutoTow Inc. (OTCPK:AUTW),4984380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,-55590,25790,28775,38501,154787,80664,-1972,79542,82448,87579,197297,113177,-17303,-14050,-15438,-5667,-5860,-2438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46502,159437,126807,31465,173573,240506

In [103]:
# Combine first two rows into a single header
new_columns = []

for col_name, fy in zip(df1.iloc[3], df1.iloc[4]):
    if pd.isna(fy):
        new_columns.append(str(col_name).strip())
    else:
        new_columns.append(f"{col_name}_{fy}".strip())

df1.columns = new_columns

new_columns = []

for col_name, fy in zip(df2.iloc[3], df2.iloc[4]):
    if pd.isna(fy):
        new_columns.append(str(col_name).strip())
    else:
        new_columns.append(f"{col_name}_{fy}".strip())

df2.columns = new_columns

In [104]:
df1 = df1.drop(df1.index[:6]).reset_index(drop = True)
df2 = df2.drop(df2.index[:6]).reset_index(drop = True)

In [105]:
print(df1.shape)
print(df2.shape)

(6463, 41)
(6465, 38)

In [106]:
df1.head()

,SP_ENTITY_NAME,SP_ENTITY_ID,SP_COMPANY_NAME,SP_ENTITY_ID,SP_TICKER,IQ_TOTAL_ASSETS_FY2025,IQ_TOTAL_ASSETS_FY2024,IQ_TOTAL_ASSETS_FY2023,IQ_TOTAL_ASSETS_FY2022,IQ_TOTAL_ASSETS_FY2021,IQ_TOTAL_ASSETS_FY2020,IQ_TOTAL_REV_FY2025,IQ_TOTAL_REV_FY2024,IQ_TOTAL_REV_FY2023,IQ_TOTAL_REV_FY2022,IQ_TOTAL_REV_FY2021,IQ_TOTAL_REV_FY2020,IQ_CASH_EQUIV_FY2025,IQ_CASH_EQUIV_FY2024,IQ_CASH_EQUIV_FY2023,IQ_CASH_EQUIV_FY2022,IQ_CASH_EQUIV_FY2021,IQ_CASH_EQUIV_FY2020,IQ_ST_DEBT_FY2025,IQ_ST_DEBT_FY2024,IQ_ST_DEBT_FY2023,IQ_ST_DEBT_FY2022,IQ_ST_DEBT_FY2021,IQ_ST_DEBT_FY2020,IQ_LT_DEBT_FY2025,IQ_LT_DEBT_FY2024,IQ_LT_DEBT_FY2023,IQ_LT_DEBT_FY2022,IQ_LT_DEBT_FY2021,IQ_LT_DEBT_FY2020,IQ_CASH_OPER_FY2025,IQ_CASH_OPER_FY2024,IQ_CASH_OPER_FY2023,IQ_CASH_OPER_FY2022,IQ_CASH_OPER_FY2021,IQ_CASH_OPER_FY2020
0,@Plan.Inc (NASDAQGM:APLN),4996297,@Plan.Inc,4996297,APLN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1606 Corp. (OTCPK:CBDW),29580758,1606 Corp.,29580758,CBDW,NaN,10.14,148.338,231.816,40.992,50.347,NaN,7.195,1.603,13.944,34.069,67.907,NaN,2.078,48.941,105.065,9.543,NaN,NaN,1553.856,1001.636,NaN,195.05,NaN,NaN,NaN,NaN,735.05,36.422,NaN,NaN,-890.986,-747.104,-610.151,-260.507,-95.289
2,1-800 AutoTow Inc. (OTCPK:AUTW),4984380,1-800 AutoTow Inc.,4984380,AUTW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,"1-800-FLOWERS.COM, Inc.",4122591,FLWS,772617,1032648,1051430,1094891,1076679,774435,1685658,1831421,2017853,2207885,2122245,1489637,46502,159437,126807,31465,173573,240506,NaN,NaN,NaN,NaN,NaN,NaN,134764,177113,186391,142497,161512,87559,-26363,94999,115351,5189,173290,139417
4,1847 Holdings LLC (OTCPK:LBRA),7019095,1847 Holdings LLC,7019095,LBRA,NaN,33647.738,39368.197,45484.699,47006.547,19239.94,NaN,15710.33,14190.135,48929.124,30660.984,8745.446,NaN,2502.45,673.445,1079.355,1383.533,976.538,NaN,578.29,578.29,362.779,NaN,391.611,NaN,8.53,23076.323,24812.629,27883.239,1637.31,NaN,-14635.636,-8023.584,-4131.477,-1333.176,-4384.135

In [107]:
df2.head()

,SP_ENTITY_NAME,SP_ENTITY_ID,IQ_EBIT_FY2025,IQ_EBIT_FY2024,IQ_EBIT_FY2023,IQ_EBIT_FY2022,IQ_EBIT_FY2021,IQ_EBIT_FY2020,IQ_EBITDA_FY2025,IQ_EBITDA_FY2024,IQ_EBITDA_FY2023,IQ_EBITDA_FY2022,IQ_EBITDA_FY2021,IQ_EBITDA_FY2020,IQ_INTEREST_EXP_FY2024,IQ_INTEREST_EXP_FY2023,IQ_INTEREST_EXP_FY2025,IQ_INTEREST_EXP_FY2022,IQ_INTEREST_EXP_FY2021,IQ_INTEREST_EXP_FY2020,PCD_TOTAL_LIAB_FY2025,PCD_TOTAL_LIAB_FY2024,PCD_TOTAL_LIAB_FY2023,PCD_TOTAL_LIAB_FY2022,PCD_TOTAL_LIAB_FY2021,PCD_TOTAL_LIAB_FY2020,IQ_ST_DEBT_FY2025,IQ_ST_DEBT_FY2024,IQ_ST_DEBT_FY2023,IQ_ST_DEBT_FY2022,IQ_ST_DEBT_FY2021,IQ_ST_DEBT_FY2020,IQ_CASH_EQUIV_FY2025,IQ_CASH_EQUIV_FY2024,IQ_CASH_EQUIV_FY2023,IQ_CASH_EQUIV_FY2022,IQ_CASH_EQUIV_FY2021,IQ_CASH_EQUIV_FY2020
0,@Plan.Inc (NASDAQGM:APLN),4996297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1606 Corp. (OTCPK:CBDW),29580758,NaN,-4116.775,-1554.972,-540.037,-301.261,-227.742,NaN,NaN,NaN,NaN,NaN,NaN,-491.385,-153.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1553.856,1001.636,NaN,195.05,NaN,NaN,2.078,48.941,105.065,9.543,NaN
2,1-800 AutoTow Inc. (OTCPK:AUTW),4984380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,-55590,25790,28775,38501,154787,80664,-1972,79542,82448,87579,197297,113177,-17303,-14050,-15438,-5667,-5860,-2438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46502,159437,126807,31465,173573,240506
4,1847 Holdings LLC (OTCPK:LBRA),7019095,NaN,-11319.069,-5250.74,-5739.508,-1103.899,-1349.897,NaN,-10663.411,-4088.445,-3702.396,-194.917,-1173.285,-13309.945,-8860.425,NaN,-4594.74,-1296.537,-249.626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,578.29,578.29,362.779,NaN,391.611,NaN,2502.45,673.445,1079.355,1383.533,976.538

In [108]:
df1 = df1.loc[:, ~df1.columns.duplicated()]
df1.head()

,SP_ENTITY_NAME,SP_ENTITY_ID,SP_COMPANY_NAME,SP_TICKER,IQ_TOTAL_ASSETS_FY2025,IQ_TOTAL_ASSETS_FY2024,IQ_TOTAL_ASSETS_FY2023,IQ_TOTAL_ASSETS_FY2022,IQ_TOTAL_ASSETS_FY2021,IQ_TOTAL_ASSETS_FY2020,IQ_TOTAL_REV_FY2025,IQ_TOTAL_REV_FY2024,IQ_TOTAL_REV_FY2023,IQ_TOTAL_REV_FY2022,IQ_TOTAL_REV_FY2021,IQ_TOTAL_REV_FY2020,IQ_CASH_EQUIV_FY2025,IQ_CASH_EQUIV_FY2024,IQ_CASH_EQUIV_FY2023,IQ_CASH_EQUIV_FY2022,IQ_CASH_EQUIV_FY2021,IQ_CASH_EQUIV_FY2020,IQ_ST_DEBT_FY2025,IQ_ST_DEBT_FY2024,IQ_ST_DEBT_FY2023,IQ_ST_DEBT_FY2022,IQ_ST_DEBT_FY2021,IQ_ST_DEBT_FY2020,IQ_LT_DEBT_FY2025,IQ_LT_DEBT_FY2024,IQ_LT_DEBT_FY2023,IQ_LT_DEBT_FY2022,IQ_LT_DEBT_FY2021,IQ_LT_DEBT_FY2020,IQ_CASH_OPER_FY2025,IQ_CASH_OPER_FY2024,IQ_CASH_OPER_FY2023,IQ_CASH_OPER_FY2022,IQ_CASH_OPER_FY2021,IQ_CASH_OPER_FY2020
0,@Plan.Inc (NASDAQGM:APLN),4996297,@Plan.Inc,APLN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1606 Corp. (OTCPK:CBDW),29580758,1606 Corp.,CBDW,NaN,10.14,148.338,231.816,40.992,50.347,NaN,7.195,1.603,13.944,34.069,67.907,NaN,2.078,48.941,105.065,9.543,NaN,NaN,1553.856,1001.636,NaN,195.05,NaN,NaN,NaN,NaN,735.05,36.422,NaN,NaN,-890.986,-747.104,-610.151,-260.507,-95.289
2,1-800 AutoTow Inc. (OTCPK:AUTW),4984380,1-800 AutoTow Inc.,AUTW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,"1-800-FLOWERS.COM, Inc.",FLWS,772617,1032648,1051430,1094891,1076679,774435,1685658,1831421,2017853,2207885,2122245,1489637,46502,159437,126807,31465,173573,240506,NaN,NaN,NaN,NaN,NaN,NaN,134764,177113,186391,142497,161512,87559,-26363,94999,115351,5189,173290,139417
4,1847 Holdings LLC (OTCPK:LBRA),7019095,1847 Holdings LLC,LBRA,NaN,33647.738,39368.197,45484.699,47006.547,19239.94,NaN,15710.33,14190.135,48929.124,30660.984,8745.446,NaN,2502.45,673.445,1079.355,1383.533,976.538,NaN,578.29,578.29,362.779,NaN,391.611,NaN,8.53,23076.323,24812.629,27883.239,1637.31,NaN,-14635.636,-8023.584,-4131.477,-1333.176,-4384.135

In [115]:
df_merged = pd.merge(df1, df2, on = "SP_ENTITY_ID", how = "inner", validate = "one_to_one")
df_merged = df_merged.drop(columns = ["SP_ENTITY_NAME_x"])
df_merged.head()

,SP_ENTITY_ID,SP_COMPANY_NAME,SP_TICKER,IQ_TOTAL_ASSETS_FY2025,IQ_TOTAL_ASSETS_FY2024,IQ_TOTAL_ASSETS_FY2023,IQ_TOTAL_ASSETS_FY2022,IQ_TOTAL_ASSETS_FY2021,IQ_TOTAL_ASSETS_FY2020,IQ_TOTAL_REV_FY2025,IQ_TOTAL_REV_FY2024,IQ_TOTAL_REV_FY2023,IQ_TOTAL_REV_FY2022,IQ_TOTAL_REV_FY2021,IQ_TOTAL_REV_FY2020,IQ_CASH_EQUIV_FY2025_x,IQ_CASH_EQUIV_FY2024_x,IQ_CASH_EQUIV_FY2023_x,IQ_CASH_EQUIV_FY2022_x,IQ_CASH_EQUIV_FY2021_x,IQ_CASH_EQUIV_FY2020_x,IQ_ST_DEBT_FY2025_x,IQ_ST_DEBT_FY2024_x,IQ_ST_DEBT_FY2023_x,IQ_ST_DEBT_FY2022_x,IQ_ST_DEBT_FY2021_x,IQ_ST_DEBT_FY2020_x,IQ_LT_DEBT_FY2025,IQ_LT_DEBT_FY2024,IQ_LT_DEBT_FY2023,IQ_LT_DEBT_FY2022,IQ_LT_DEBT_FY2021,IQ_LT_DEBT_FY2020,IQ_CASH_OPER_FY2025,IQ_CASH_OPER_FY2024,IQ_CASH_OPER_FY2023,IQ_CASH_OPER_FY2022,IQ_CASH_OPER_FY2021,IQ_CASH_OPER_FY2020,SP_ENTITY_NAME_y,IQ_EBIT_FY2025,IQ_EBIT_FY2024,IQ_EBIT_FY2023,IQ_EBIT_FY2022,IQ_EBIT_FY2021,IQ_EBIT_FY2020,IQ_EBITDA_FY2025,IQ_EBITDA_FY2024,IQ_EBITDA_FY2023,IQ_EBITDA_FY2022,IQ_EBITDA_FY2021,IQ_EBITDA_FY2020,IQ_INTEREST_EXP_FY2024,IQ_INTEREST_EXP_FY2023,IQ_INTEREST_EXP_FY2025,IQ_INTEREST_EXP_FY2022,IQ_INTEREST_EXP_FY2021,IQ_INTEREST_EXP_FY2020,PCD_TOTAL_LIAB_FY2025,PCD_TOTAL_LIAB_FY2024,PCD_TOTAL_LIAB_FY2023,PCD_TOTAL_LIAB_FY2022,PCD_TOTAL_LIAB_FY2021,PCD_TOTAL_LIAB_FY2020,IQ_ST_DEBT_FY2025_y,IQ_ST_DEBT_FY2024_y,IQ_ST_DEBT_FY2023_y,IQ_ST_DEBT_FY2022_y,IQ_ST_DEBT_FY2021_y,IQ_ST_DEBT_FY2020_y,IQ_CASH_EQUIV_FY2025_y,IQ_CASH_EQUIV_FY2024_y,IQ_CASH_EQUIV_FY2023_y,IQ_CASH_EQUIV_FY2022_y,IQ_CASH_EQUIV_FY2021_y,IQ_CASH_EQUIV_FY2020_y
0,4996297,@Plan.Inc,APLN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@Plan.Inc (NASDAQGM:APLN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29580758,1606 Corp.,CBDW,NaN,10.14,148.338,231.816,40.992,50.347,NaN,7.195,1.603,13.944,34.069,67.907,NaN,2.078,48.941,105.065,9.543,NaN,NaN,1553.856,1001.636,NaN,195.05,NaN,NaN,NaN,NaN,735.05,36.422,NaN,NaN,-890.986,-747.104,-610.151,-260.507,-95.289,1606 Corp. (OTCPK:CBDW),NaN,-4116.775,-1554.972,-540.037,-301.261,-227.742,NaN,NaN,NaN,NaN,NaN,NaN,-491.385,-153.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1553.856,1001.636,NaN,195.05,NaN,NaN,2.078,48.941,105.065,9.543,NaN
2,4984380,1-800 AutoTow Inc.,AUTW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-800 AutoTow Inc. (OTCPK:AUTW),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4122591,"1-800-FLOWERS.COM, Inc.",FLWS,772617,1032648,1051430,1094891,1076679,774435,1685658,1831421,2017853,2207885,2122245,1489637,46502,159437,126807,31465,173573,240506,NaN,NaN,NaN,NaN,NaN,NaN,134764,177113,186391,142497,161512,87559,-26363,94999,115351,5189,173290,139417,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",-55590,25790,28775,38501,154787,80664,-1972,79542,82448,87579,197297,113177,-17303,-14050,-15438,-5667,-5860,-2438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46502,159437,126807,31465,173573,240506
4,7019095,1847 Holdings LLC,LBRA,NaN,33647.738,39368.197,45484.699,47006.547,19239.94,NaN,15710.33,14190.135,48929.124,30660.984,8745.446,NaN,2502.45,673.445,1079.355,1383.533,976.538,NaN,578.29,578.29,362.779,NaN,391.611,NaN,8.53,23076.323,24812.629,27883.239,1637.31,NaN,-14635.636,-8023.584,-4131.477,-1333.176,-4384.135,1847 Holdings LLC (OTCPK:LBRA),NaN,-11319.069,-5250.74,-5739.508,-1103.899,-1349.897,NaN,-10663.411,-4088.445,-3702.396,-194.917,-1173.285,-13309.945,-8860.425,NaN,-4594.74,-1296.537,-249.626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,578.29,578.29,362.779,NaN,391.611,NaN,2502.45,673.445,1079.355,1383.533,976.538

In [121]:
import re
id_cols = ["SP_ENTITY_ID", "SP_COMPANY_NAME", "SP_TICKER"]
value_cols = [
    c for c in df_merged.columns
    if re.search(r"_FY\d{4}(_[xy])?$", c)]

#MELTING THE DATA

In [129]:
df_long = df_merged.melt(id_vars = id_cols, value_vars = value_cols, var_name = "variable", value_name = "value")
df_long["fiscal_year"] = ( df_long["variable"].str.extract(r"_fy(\d{4})", flags = re.IGNORECASE))
df_long["fiscal_year"] = df_long["fiscal_year"].astype("Int64")

In [135]:
df_long["base_variable"] = (df_long["variable"].str.lower()
                            .str.replace(r"_fy\d{4}", "", regex=True)
                            .str.replace(r"_[xy]$", "", regex=True))
df_long[["base_variable","fiscal_year"]].head()

     base_variable  fiscal_year
0  iq_total_assets         2025
1  iq_total_assets         2025
2  iq_total_assets         2025
3  iq_total_assets         2025
4  iq_total_assets         2025

In [140]:
df_panel = df_long.pivot_table(
    index = id_cols + ["fiscal_year"],
    columns = "base_variable",
    values = "value",
    aggfunc = "first").reset_index()
df_panel.columns.name = None
df_panel = df_panel.sort_values(
    ["SP_ENTITY_ID", "fiscal_year"]
).reset_index(drop=True)

df_panel.head()

   SP_ENTITY_ID   SP_COMPANY_NAME SP_TICKER  fiscal_year iq_cash_equiv iq_cash_oper iq_ebit iq_ebitda iq_interest_exp iq_lt_debt iq_st_debt iq_total_assets iq_total_rev pcd_total_liab
0        103697  GATX Corporation      GATX         2020        292200       428300  285500    627700         -191800    5329000      23600         8937600      1209200            NaN
1        103697  GATX Corporation      GATX         2021        344300       507200  292200    670600         -204700    5887500      18100         9541700      1257400            NaN
2        103697  GATX Corporation      GATX         2022        303700       533500  330100    701400         -220400    6431500      17300        10072000      1273000            NaN
3        103697  GATX Corporation      GATX         2023        450700       520400  390500    782600         -278600    7388100      11000        11326000      1410900            NaN
4        103697  GATX Corporation      GATX         2024        401600       602100  477700    899100         -365300    8215300      10400        12296500      1585500            NaN

In [141]:
df_panel.shape

(10459, 14)

In [142]:
df_panel.to_csv(r"C:\Users\Ozoha\Documents\.ipynb_checkpoints\credit-risk-ews\data\firm_year_panel.csv", index = False)